name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Update Listing Page"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: updated-html
        path: .

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin main
